### ISSUE TITLE
Error Code 504 - default installation + ingress

### ISSUE THREAD

**Issue by NILAXY** [gimlet-io/capacitor#86] opened 2024-04-08 21:24 UTC
Hi, i wanted to try out capacitor and installed it with the provided manifests to flux. It runs without a problem and no errors can be seen in the logs. So i created a simple ingress which is connected to the service created from capacitor but it loads a few seconds and then just returns 504.

Ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capacitor-ingress
  namespace: flux-system
spec:
  rules:
    - host: example.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: capacitor
                port:
                  number: 9000
```

Manifests:
```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/gimlet-io/capacitor-manifests
  ref:
    semver: ">=0.1.0"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  path: "./"
  sourceRef:
    kind: OCIRepository
    name: capacitor

```

Logs:
```
W0408 20:07:14.840830       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2024-04-08T20:07:14.893899002Z time="2024-04-08T20:07:14Z" level=info msg="Starting gitrepositories.source.toolkit.fluxcd.io controller"
2024-04-08T20:07:14.898081843Z time="2024-04-08T20:07:14Z" level=info msg="Starting ocirepositories.source.toolkit.fluxcd.io controller"
2024-04-08T20:07:14.900842470Z time="2024-04-08T20:07:14Z" level=info msg="Starting buckets.source.toolkit.fluxcd.io controller"
2024-04-08T20:07:14.917349112Z time="2024-04-08T20:07:14Z" level=info msg="Starting kustomizations.kustomize.toolkit.fluxcd.io controller"
2024-04-08T20:07:14.939218047Z time="2024-04-08T20:07:14Z" level=info msg="Starting helmreleases.helm.toolkit.fluxcd.io controller"
2024-04-08T20:07:14.939254248Z time="2024-04-08T20:07:14Z" level=info msg="Starting event controller"
2024-04-08T20:07:14.939287768Z time="2024-04-08T20:07:14Z" level=info msg="Starting deployment controller"
2024-04-08T20:07:14.939359569Z time="2024-04-08T20:07:14Z" level=info msg="Starting pod controller"
2024-04-08T20:07:14.939366929Z time="2024-04-08T20:07:14Z" level=info msg="Starting service controller"
2024-04-08T20:07:14.939495170Z time="2024-04-08T20:07:14Z" level=info msg="Starting ingress controller"
2024-04-08T20:07:14.939677092Z time="2024-04-08T20:07:14Z" level=info msg=Initialized
```

**Comment by holtakj** [comment] 2024-05-09 18:49
same here. Is it possible that capacitor can not deal with a HTTP/2.0 connection?

**Comment by sebastiangaiser** [comment] 2024-05-09 19:10
Should be a duplicate of https://github.com/gimlet-io/capacitor/issues/38 
I think you're missing the NetworkPolicy...

**Comment by holtakj** [comment] 2024-05-09 19:18
thanks. that was it.

**Comment by sebastiangaiser** [comment] 2024-05-23 19:11
@NILAXY you reacted with a 👍🏻 on my comment. Can you please close the issue because it's a duplicate

**Closed** 2024-05-24 01:20 UTC
